// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type lbEndpoint struct {
	Ip  uint32
	Mac [6]uint8
	_   [2]byte
}

type lbFourTupleT struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
}

// loadLb returns the embedded CollectionSpec for lb.
func loadLb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lb: %w", err)
	}

	return spec, err
}

// loadLbObjects loads lb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lbObjects
//	*lbPrograms
//	*lbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLbObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbSpecs struct {
	lbProgramSpecs
	lbMapSpecs
	lbVariableSpecs
}

// lbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbProgramSpecs struct {
	XdpLoadBalancer *ebpf.ProgramSpec `ebpf:"xdp_load_balancer"`
}

// lbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbMapSpecs struct {
	Backends     *ebpf.MapSpec `ebpf:"backends"`
	Flows        *ebpf.MapSpec `ebpf:"flows"`
	LoadBalancer *ebpf.MapSpec `ebpf:"load_balancer"`
}

// lbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbVariableSpecs struct {
}

// lbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbObjects struct {
	lbPrograms
	lbMaps
	lbVariables
}

func (o *lbObjects) Close() error {
	return _LbClose(
		&o.lbPrograms,
		&o.lbMaps,
	)
}

// lbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbMaps struct {
	Backends     *ebpf.Map `ebpf:"backends"`
	Flows        *ebpf.Map `ebpf:"flows"`
	LoadBalancer *ebpf.Map `ebpf:"load_balancer"`
}

func (m *lbMaps) Close() error {
	return _LbClose(
		m.Backends,
		m.Flows,
		m.LoadBalancer,
	)
}

// lbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbVariables struct {
}

// lbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbPrograms struct {
	XdpLoadBalancer *ebpf.Program `ebpf:"xdp_load_balancer"`
}

func (p *lbPrograms) Close() error {
	return _LbClose(
		p.XdpLoadBalancer,
	)
}

func _LbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lb_bpf.o
var _LbBytes []byte
